//import { Lead } from "./Lead";
export class LeadView {
  id: string;
  date: string;
  name: string;
  totalexp:string;
  phoneNumber: string;
  email: string;
  status: string;
  classestaken: string;
  ratings:Number;
  timeslots: string;
  leadId: string;
  slots:string;
  classesTaken:number;
  leadType : Number;
  cosmos_ref: string;
  type:string;
  batchCode: string;
  studentID: string;
  dob: string;
  whatsapp: string;
  address: string;
  classType: string;
  payments: string;
  age: string;
  startDate: Date;
  startLesson: string;
  pfirstName: string;
  plastName: string;
  course: string;
  comments: string;
  alternativeMobile: string;
  paymentid: string;
  downpayment: string;
  classessold: string;
  saleamount: string;
  plantype: string;
  studentId: string;
  Id: string;
  firstName: string;
  lastName: string;
  teacherName: string;
  days: string;
  studentType: string;
  firstFeedback: string;
  public constructor(id:string, leadId:string, date:string,name:string,experience:string, mobile:string,email:string,status:string,classestaken:number,
      ratings:number,slots:string,leadType:number, type:string, batchCode:string, studentID:string, dob?:string, whatsapp?: string, address?: string, classType?: string, payments?: string, age?: string, startDate?: Date, startLesson?: string, pfirstName?: string, plastName?: string, course?: string, comments?: string, alternativeMobile?: string, paymentid?: string,  firstName?:string, lastName?:string, teacherName?: string, days?: string, studentType?: string, firstFeedback?: string) {
      this.id = id;
      this.leadId = leadId;
      this.date = date;
      this.totalexp=experience;
      this.phoneNumber=mobile;
      this.email=email;
      this.status=status;
      this.classesTaken=classestaken;
      this.ratings=ratings;
      this.slots=slots;
      this.slots=slots;
      this.type = type;
      this.leadType = leadType;
      this.name = name;
      this.batchCode = batchCode;
      this.studentID = studentID;
      this.dob = dob;
      this.whatsapp = whatsapp;
      this.address = address;
      this.classType = classType;
      this.payments = payments;
      if(Array.isArray(payments)){
          this.paymentid = payments.map(p => p.paymentid).join(',');
          this.downpayment = payments.map(p => p.downpayment).join(',');
          this.classessold = payments.map(p => p.classessold).join(',');
          this.saleamount = payments.map(p => p.saleamount).join(',');
          this.plantype = payments.map(p => p.plantype).join(',');
          this.studentId = payments.map(p => p.studentId).join(',');
      }
      this.age = age;
      this.startDate = startDate;
      this.startLesson = startLesson;
      this.pfirstName = pfirstName;
      this.plastName = plastName;
      this.course = course;
      this.comments = comments;
      this.alternativeMobile = alternativeMobile;
      // this.paymentid = paymentid;
      this.firstName = firstName;
      this.lastName = lastName;
      this.teacherName = teacherName;
      this.days = days;
      this.studentType = studentType;
      this.firstFeedback = firstFeedback;
  }
}