import { Schema, model } from "mongoose";

export interface Trial {
  lead_id: string;
  sName: string;
  pName: string;
  phone: string;
  address: string;
  aPhone: string;
  wNumber: string;
  pEmail?: string;
  gender: string;
  grade: string;
  source: string;
  city?: string;
  placementTests: any;
}

const trialSchema = new Schema<any>(
  {
    lead_id: String,
    sName: {
      type: String,
      required: true,
    },
    pName: {
      type: String,
      required: true,
    },
    phone: {
      type: String,
      required: true,
    },
    aPhone: {
      type: String,
    },
    wNumber: {
      type: String,
    },
    pEmail: {
      type: String,
      required: false,
      default: "",
    },
    address: {
      type: String,
      required: false,
    },
    gender: {
      type: String,
      required: true,
    },
    grade: {
      type: String,
      required: true,
    },
    source: {
      type: String,
      required: true,
    },
    city: {
      type: String,
      required: false,
    },
    bDate: {
      type: Date,
      required: true,
    },
    bTime: {
      type: String,
      required: true,
    },
    duplicateProtection: {
      type: Number,
    },
    isDoubleBookingAllowed: {
      type: Boolean,
      default: true,
    },
    bComments: String,
    tComments: String,
    email: {
      type: String,
      required: false,
      default: "",
    },
    attendanceStatus: {
      type: String,
      enum: ["Will Attend", "Not Confirmed", "Auto Confirmed"],
      default: "Not Confirmed",
    },
    attendance: {
      type: String,
      enum: [
        "No Show",
        "Less than 15 min",
        "Partially attended",
        "Fully attended",
        "Cancelled by QE",
      ],
    },
    attendanceReason: {
      type: String,
      enum: [],
    },
    attendanceScore: {
      type: Number,
      dfault: 0,
    },
    placementTests: {
      type: Map,
      default: {
        noTest: {
          name: "No Placement Test Required",
          active: false,
        },
        level1A: {
          name: "Level 1 - Part A",
          active: false,
          score: 0,
          totalScore: 40,
        },
        level1B: {
          name: "Level 1 - Part B",
          active: false,
          score: 0,
          totalScore: 8,
        },
        level2: {
          name: "Level 2",
          active: false,
          score: 0,
          totalScore: 14,
        },
      },
    },
    attendanceStatusUpdate: {
      type: String,
    },
    trialStatus: {
      type: String,
      enum: [
        "Ready For Trial",
        "Trial Aborted",
        "Trial Completed",
        "Trial On Hold",
        "Requested Reschedule",
      ],
      default: "Ready For Trial",
    },
    bTimestamp: {
      type: Number,
      required: true,
    },
    skipGradeCheck: {
      type: Number,
    },
    RefID: {
      type: String,
    },
    messageSentToTeacher: Boolean,
    messageSentToStudent: Boolean,
    bookingAgentEmail: String,
    trialId: {
      type: String,
      required: true,
      unique: true,
    },
    personalTrial: {
      type: Boolean,
      default: false,
    },
    autoGenerated: Boolean,
    refLeadSource: {
      type: String,
    },
    zoomMethod: {
      type: String,
    },
    ISVLink: {
      type: Schema.Types.ObjectId,
      ref: "zoom-link",
    },
    rescheduleAttempts: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true,
  }
);

const Trial = model("trial", trialSchema);

export default Trial;
